### PR TITLE
Add ALP aarch64 images

### PR DESCRIPTION
**Pull request by jlausuch**

### CODE REVIEW

**Comment by jlausuch** [comment]
@ggardet @mloviska

**Comment by jlausuch** [comment]
> LGTM. Thanks!

I dont' have rights to merge, can you please do so?

**Comment by jlausuch** [comment]
> > > LGTM. Thanks!
> > 
> > 
> > I dont' have rights to merge, can you please do so?
> 
> I cannot either!

maybe @andrii-suse  ?

**Comment by andrii-suse** [comment]
> Do we need to run scriptgen in O3 again?

If you look at read_files.sh at https://openqa.opensuse.org/admin/obs_rsync/devel:LEO%7Cbase - it has only x86_64 in it, so yeah the scripts must be regenerated with scriptgen manually, it doesn't happen automatically atm

**Pull request merged**
