### PR TITLE
Add CR-DVD Image flavor to Leap 15.4

### PR DESCRIPTION
**Pull request by DeepthiYV**
Progress Ticket: https://progress.opensuse.org/issues/120243

### CODE REVIEW

**Comment by DeepthiYV** [comment]
@foursixnine @Vogtinator 
Kindly review my PR.

**Comment by Vogtinator** [comment]
To avoid conflicts you'll have to remove the other sync completely. There's also more content in the other XML, like `news` and `repos`.

**Comment by Vogtinator** [comment]
I see it rsyncs all four isos but only does isos/post for aarch64 and x86_64?

**Comment by DeepthiYV** [comment]
> To avoid conflicts you'll have to remove the other sync completely. There's also more content in the other XML, like `news` and `repos`.

I did not understand this. Are you asking me to remove the sync of whatever I have added earlier, or the sync that are present in the openSUSE:Leap:15.4:Images:ToTest?

**Comment by Vogtinator** [comment]
LGTM. Can you add the revert from #216 here?

**Pull request merged**
