### PR TITLE
Use SUSE:ALP:ToTest instead of SUSE:ALP

### PR DESCRIPTION
**Pull request by ggardet**
and make use of Snapshot.* naming scheme

This is a follow-up of #192

### CODE REVIEW

**Comment by ggardet** [comment]
Thanks @andrii-suse !

**Comment by jlausuch** [comment]
@ggardet can you fix conflicts and we can merge?

**Comment by ggardet** [comment]
> @ggardet can you fix conflicts and we can merge?

Rebased

**Review by jlausuch — APPROVED** [review]

**Comment by jlausuch** [comment]
@mloviska @foursixnine

**Comment by jlausuch** [comment]
anyone with merge rights?

**Pull request merged**
