### PR TITLE
Add aarch64 media to openSUSE:Jump:15.2:Images

### PR DESCRIPTION
**Pull request by Vogtinator**
Needed some workarounds, see comments in openSUSE:Jump:15:Images.xml.

### CODE REVIEW

**Review by okurz — APPROVED** [review]

**Review by Martchus — APPROVED** [review]

**Comment by okurz** [comment]
I had put an automatic cron job in place on o3 to automatically update. @Vogtinator please check if that works as expected.

**Comment by Vogtinator** [comment]
> I had put an automatic cron job in place on o3 to automatically update. @Vogtinator please check if that works as expected.

It almost did - `t/obs/openSUSE:Jump:15.2:Images:ToTest` was owned by root, so git pull failed. I cleaned that up and the deployment worked. For some reason the syncing didn't result in scheduled products though - https://openqa.opensuse.org/admin/obs_rsync/openSUSE:Jump:15.2:Images:ToTest/runs/.run_last/download/openqa.cmd is correct, but there's no corresponding `.log` file...

**Comment by Vogtinator** [comment]
Looks like rsyncing failed, but that's only visible when looking through all log files:

```
+ rsync --timeout=3600 -tlp4 --specials 'obspublish::openqa/openSUSE:Jump:15.2:Images:ToTest/images/*/*vagrant*libvirt*/Leap-15.2.aarch64-15.2-libvirt_aarch64-Build2.1.vagrant.libvirt.box' /var/lib/openqa/factory/other/
rsync: link_stat "/openSUSE:Jump:15.2:Images:ToTest/images/x86_64/kiwi-images-vagrant:libvirt/Leap-15.2.aarch64-15.2-libvirt_aarch64-Build2.1.vagrant.libvirt.box" (in openqa) failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1674) [generator=3.1.3]
```

I'll have a look at that tomorrow.

**Comment by andrii-suse** [comment]
Not sure why rsync doesn't like last command and tries to find aarch64 binary in /x86_64/ folder.
I've worked around script generation to let the tests start and will investigate proper solution.
(If you remove `GENERATED FILE` from header from one of `print*.sh` script - it will not be overwritten by `make` command and will remain custom. So current version just ignores that weird error from rsync - edited only pre-last line https://openqa.opensuse.org/admin/obs_rsync/openSUSE:Jump:15.2:Images:ToTest/runs/.run_last/download/print_rsync_iso.sh ).

**Pull request merged**
