### PR TITLE
Download selfinstall iso

### PR DESCRIPTION
**Pull request by mloviska**
SelfInstall Leap Micro test should boot iso instead of raw images.
More info in https://bugzilla.opensuse.org/show_bug.cgi?id=1197877

### CODE REVIEW

**Comment by mloviska** [comment]
@jlausuch @nilxam

**Review by jlausuch — APPROVED** [review]
LGTM!

**Comment by jlausuch** [comment]
@andrii-suse @Martchus could you please merge?

**Comment by andrii-suse** [comment]
Hm, it looks `Default-SelfInstall` is not synced anymore and has no `isos post` as well. It is certainly possible that such combination is not supported by generation, I will have a look

**Review by andrii-suse — CHANGES_REQUESTED** [review]
Ah it looks the xml has `raw.xz` for Default-SelfInstall , but .lst file has `iso` : `Default-SelfInstall-Build16.23.install.iso` . Which one is correct?

**Comment by mloviska** [comment]
> Ah it looks the xml has `raw.xz` for Default-SelfInstall , but .lst file has `iso` : `Default-SelfInstall-Build16.23.install.iso` . Which one is correct?

Made a mistake there, I should update only `SelfInstall` flavors. Thanks!

**Review by andrii-suse — APPROVED** [review]

**Pull request merged**
