### PR TITLE
Remove .install suffix for repo files on MicroOS-SelfInstall flavor

### PR DESCRIPTION
**Pull request by tinawang123**
* Related ticket: https://progress.opensuse.org/issues/170158
* Related PR: https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/20748

### CODE REVIEW

**Comment by okurz** [comment]
Please adjust your commit message to be more specific. It reads like you would change *all* repo files :)

**Comment by Martchus** [comment]
You only changed the PR title. However, I'm wondering whether this change actually *is* MicroOS-SelfInstall specific. Looking at the code I'm more under the impression that this will change more than that.

**Comment by andrii-suse** [comment]
It seemed tricky, so I tried to reproduce and apparently the fix was rather simple, so I submitted #280 , I guess this one can be closed.

**Comment by tinawang123** [comment]
Close this PR, as only impact one job, I will update job settings.

**Pull request closed without merging**
