### PR TITLE
ALP is now being developed in SUSE:ALP

### PR DESCRIPTION
**Pull request by jlausuch**
ALP is now being developed in SUSE:ALP

For the september release, only KMV image will be shipped.

For now, there is only x86_64 image available. When other images flavors and architectures become available, we can add them to this xml.

### CODE REVIEW

**Comment by jlausuch** [comment]
@andrii-suse @foursixnine @jknphy

**Comment by jlausuch** [comment]
The ci complains that `Cannot find xml file for t/obs/devel:LEO .`
Not sure why if I have removed that file and directory...

**Comment by jknphy** [comment]
I tried your branch in local and the folder is not there, but still I got similar error with another one:
`t/obs/openSUSE:Leap:15.2:WSL` strange...

**Comment by jlausuch** [comment]
Let's remove it first: https://github.com/os-autoinst/openqa-trigger-from-obs/pull/181

**Comment by jlausuch** [comment]
@foursixnine @jknphy   As removing stuff does not work, let's just merge this and worry about removing left overs later on.

**Comment by foursixnine** [comment]
@jlausuch I'll merge the other one too

**Pull request merged**
