### PR TITLE
Add Leap 16.0

### PR DESCRIPTION
**Pull request by lkocman**
* we'll be newly testing agama-installer (was agama-installer-openSUSE) from openSUSE:Leap:16.0:ToTest. Images:ToTest will be for remaining appliances

Initialy redudant to https://github.com/os-autoinst/openqa-trigger-from-obs/pull/254/files ... which will be from now used for other images than installer.

### CODE REVIEW

**Review by nilxam — APPROVED** [review]

**Comment by foursixnine** [comment]
with https://github.com/os-autoinst/opensuse-jobgroups/pull/506 merged, we can merge this too I guess?

**Comment by lkocman** [comment]
@foursixnine please do so, we don't have rights to do so.

**Comment by foursixnine** [comment]
@lkocman you're getting the rights for future situations :)

**Comment by lkocman** [comment]
hehe many thanks @foursixnine !

**Pull request merged**
