### PR TITLE
Add aarch64 to ALP

### PR DESCRIPTION
**Pull request by ggardet**
Requires https://github.com/os-autoinst/opensuse-jobgroups/pull/233

### CODE REVIEW

**Comment by ggardet** [comment]
I think the CI fails because there is a mismatch in build numbers in OBS.

**Comment by Martchus** [comment]
This change also affects many x86-related lines. I'm not very familiar with how all of this works but are you sure?

**Comment by ggardet** [comment]
> This change also affects many x86-related lines. I'm not very familiar with how all of this works but are you sure?

It looks like it removes duplicates only.

**Comment by andrii-suse** [comment]
> It looks like it removes duplicates only.

Exactly. Presence of .license folders in files_repo.lst started causing those duplicates. Adding `$` at https://github.com/os-autoinst/openqa-trigger-from-obs/pull/192/files#diff-4d9910c8d9edac07b3908da7c83a0f329a41581b7282d170d73559ac3b1e7d90R162 now removes them.

**Pull request merged**
