### PR TITLE
Add Leap:15.5:ARM for armv7

### PR DESCRIPTION
**Pull request by ggardet**
I cannot run locally `read_files.sh` script. Help is welcome!

### CODE REVIEW

**Comment by Vogtinator** [comment]
I ran it locally, this is the only change:

```
diff --git a/t/obs/openSUSE:Leap:15.5:ARM:ToTest/files_iso.lst b/t/obs/openSUSE:Leap:15.5:ARM:ToTest/files_iso.lst
index e69de29..e63dba1 100644
--- a/t/obs/openSUSE:Leap:15.5:ARM:ToTest/files_iso.lst
+++ b/t/obs/openSUSE:Leap:15.5:ARM:ToTest/files_iso.lst
@@ -0,0 +1 @@
+openSUSE-Leap-15.5-NET-armv7hl-Build28.3-Media.iso
```

**Comment by ggardet** [comment]
> I ran it locally, this is the only change:
> 
> ```
> diff --git a/t/obs/openSUSE:Leap:15.5:ARM:ToTest/files_iso.lst b/t/obs/openSUSE:Leap:15.5:ARM:ToTest/files_iso.lst
> index e69de29..e63dba1 100644
> --- a/t/obs/openSUSE:Leap:15.5:ARM:ToTest/files_iso.lst
> +++ b/t/obs/openSUSE:Leap:15.5:ARM:ToTest/files_iso.lst
> @@ -0,0 +1 @@
> +openSUSE-Leap-15.5-NET-armv7hl-Build28.3-Media.iso
> ```

Ok, thanks. I updated my PR thanks to this update. I feel there should be something in `t/obs/openSUSE:Leap:15.5:ARM:ToTest/print_rsync_repo.before` though.

**Comment by Vogtinator** [comment]
Oh, there's actually an untracked file, so it didn't show up in `git diff`:

```
diff --git a/t/obs/openSUSE:Leap:15.5:ARM:ToTest/files_repo_Leap-ftp-ftp.lst b/t/obs/openSUSE:Leap:15.5:ARM:ToTest/files_repo_Leap-ftp-ftp.lst
new file mode 100644
index 0000000..7c68382
--- /dev/null
+++ b/t/obs/openSUSE:Leap:15.5:ARM:ToTest/files_repo_Leap-ftp-ftp.lst
@@ -0,0 +1,4 @@
+openSUSE-Leap-15.5-armv7hl-Media1.license
+openSUSE-Leap-15.5-armv7hl-Media1
+openSUSE-Leap-15.5-armv7hl-Media2
+openSUSE-Leap-15.5-armv7hl-Media3
```

**Comment by ggardet** [comment]
Thanks! 
I think it should be good now.

**Pull request merged**
