### PR TITLE
Update trigger for LEAPM 6.0

### PR DESCRIPTION
**Pull request by lkocman**
* Drop testing of install DVD which is no longer part of distro Instead of Install DVD we only have PackagesDVD

### CODE REVIEW

**Review by okurz — COMMENTED** [review]
Looks like you need to update the test files as well? See the CI failure

**Comment by grisu48** [comment]
I think the failure comes from the deletion of `xml/obs/openSUSE:Leap:Micro.xml`. This file is needed IIRC.

**Comment by lkocman** [comment]
I'll look into this this morning (after meeting marathon). Thank you folks!

**Comment by jlausuch** [comment]
The images seem to be there:
```
sudo -u geekotest rsync --password-file rsync.secret -4 --list-only obspublish::openqa/openSUSE:Leap:Micro:6.0:ToTest/images/x86_64/*/ | grep -E "raw$|xz$|qcow2$|vmdk$|vmx$"
-rw-r--r--    871,516,704 2024/04/10 22:50:06 openSUSE-Leap-Micro.x86_64-6.0-Base-Build7.1.raw.xz
-rw-r--r--    876,171,084 2024/04/10 22:52:57 openSUSE-Leap-Micro.x86_64-6.0-Base-SelfInstall-Build7.1.raw.xz
-rw-r--r--    884,167,888 2024/04/10 22:50:07 openSUSE-Leap-Micro.x86_64-6.0-Base-VMware-Build7.1.vmdk.xz
-rw-r--r--            513 2024/04/10 22:50:07 openSUSE-Leap-Micro.x86_64-6.0-Base-VMware-Build7.1.vmx
-rw-r--r--  4,294,967,296 2024/04/10 22:49:48 openSUSE-Leap-Micro.x86_64-6.0-Base-encrypted-Build7.1.raw
-rw-r--r--  1,041,956,864 2024/04/10 22:49:21 openSUSE-Leap-Micro.x86_64-6.0-Base-qcow-Build7.1.qcow2
-rw-r--r--  1,028,542,084 2024/04/10 22:52:06 openSUSE-Leap-Micro.x86_64-6.0-Default-Build7.1.raw.xz
-rw-r--r--  1,028,725,284 2024/04/10 22:56:03 openSUSE-Leap-Micro.x86_64-6.0-Default-SelfInstall-Build7.1.raw.xz
-rw-r--r--  1,033,338,972 2024/04/10 22:52:35 openSUSE-Leap-Micro.x86_64-6.0-Default-VMware-Build7.1.vmdk.xz
-rw-r--r--            513 2024/04/10 22:52:35 openSUSE-Leap-Micro.x86_64-6.0-Default-VMware-Build7.1.vmx
-rw-r--r--  4,294,967,296 2024/04/10 22:50:46 openSUSE-Leap-Micro.x86_64-6.0-Default-encrypted-Build7.1.raw
-rw-r--r--  1,300,365,312 2024/04/10 22:51:07 openSUSE-Leap-Micro.x86_64-6.0-Default-qcow-Build7.1.qcow2
```

1) I don't see RT  images being built
2) There is a new flavor `Default-encrypted` that needs to be added
3) There is a new flavor `Default-qcow` to be added
4) The old `MicroOS-Image` flavor should be replaced by `Default`
5) There are 2 types of images, do we want to sync also the `Base` flavors or just `Default`?

**Comment by lkocman** [comment]
I'm not sure about content of t/obs ... I simply took 5.5 Images and bumped 5.5.0 -> 6.0, 5.5 -> 6.0 and referenced last published build 13.1

**Review by jlausuch — APPROVED** [review]
Now it looks very good. Let's start with the `Default` images, and if you want later on you we can add `Base` images. As far as I know, `Default` ones contain hypervisor pre-installed, so they are more "complete" images, where we can run virt tests directly.

**Comment by jlausuch** [comment]
There was a mistake. RT images are only available in base flavor.
Follow-up: https://github.com/os-autoinst/openqa-trigger-from-obs/pull/247

**Pull request merged**
