### PR TITLE
MinimalVM: sync Cloud images for aarch64 and x86_64

### PR DESCRIPTION
**Pull request by mloviska**
Add to test pipeline MinimalVM cloud images for aarch64 and x86_64 to be tested in QEMU with cloud init

### CODE REVIEW

**Comment by mloviska** [comment]
@ggardet could you please have a look? Apparently the DVD flavor does not contain any ISO that could be used

```
/usr/bin/openqa-cli api -X post isos?async=1 \
 ARCH=armv7hl \
 BUILD=20240604 \
 DISTRI=opensuse \
 FLAVOR=DVD \
 FULLURL=1 \
 MIRROR_HTTP=http://openqa.opensuse.org/assets/repo/openSUSE-Tumbleweed-oss-armv7hl- \
 MIRROR_HTTPS=https://openqa.opensuse.org/assets/repo/openSUSE-Tumbleweed-oss-armv7hl- \
 MIRROR_PREFIX=http://openqa.opensuse.org/assets/repo \
 REPO_0=openSUSE-Tumbleweed-oss-armv7hl- \
 REPO_1=openSUSE-Tumbleweed-oss-armv7hl.license- \
 REPO_2=openSUSE-Tumbleweed-oss-armv7hl--debuginfo \
 REPO_3=openSUSE-Tumbleweed-oss-armv7hl--source \
 REPO_OSS=openSUSE-Tumbleweed-oss-armv7hl- \
 REPO_OSS_DEBUGINFO=openSUSE-Tumbleweed-oss-armv7hl--debuginfo \
 REPO_OSS_DEBUGINFO_PACKAGES='java*,kernel-default-debug*,kernel-default-base-debug*,mraa-debug*,wicked-debug*' \
 REPO_OSS_SOURCE=openSUSE-Tumbleweed-oss-armv7hl--source \
 REPO_OSS_SOURCE_PACKAGES='coreutils*,yast2-network*' \
 SUSEMIRROR=http://openqa.opensuse.org/assets/repo/openSUSE-Tumbleweed-oss-armv7hl- \
 VERSION=Tumbleweed \
 _OBSOLETE=1
 ```

**Comment by ggardet** [comment]
> @ggardet could you please have a look? Apparently the DVD flavor does not contain any ISO that could be used

This is expected for armv7.
We have DVD ISO for aarch64 and NET ISO for aarch64 and armv7.

**Review by ricardobranco777 — APPROVED** [review]

**Comment by mloviska** [comment]
> > @ggardet could you please have a look? Apparently the DVD flavor does not contain any ISO that could be used
> 
> This is expected for armv7. We have DVD ISO for aarch64 and NET ISO for aarch64 and armv7.

The issue is that the CI will fail for any other new PR as the DVD is no longer available

**Comment by ggardet** [comment]
> > > @ggardet could you please have a look? Apparently the DVD flavor does not contain any ISO that could be used
> > 
> > 
> > This is expected for armv7. We have DVD ISO for aarch64 and NET ISO for aarch64 and armv7.
> 
> The issue is that the CI will fail for any other new PR as the DVD is no longer available

It never existed.

**Comment by ggardet** [comment]
> > It never existed.
> 
> So the CI failures were ignored until now?

Where do you see the failure?

**Comment by mloviska** [comment]
> > > It never existed.
> > 
> > 
> > So the CI failures were ignored until now?
> 
> Where do you see the failure?

I have done no changes, just regenerated the files lists

```
P:obs/openSUSE:Factory:ARM:ToTest/base/ test_iso_consistent.sh
F-obs/openSUSE:Factory:ARM:ToTest/base/ test_repo_consistent.sh:Referenced REPO file wasnt found in print_rsync_repo output {openSUSE-Tumbleweed-oss-armv7hl--debuginfo}   {openSUSE-Tumbleweed-oss-aarch64.license-Snapshot20240604
openSUSE-Tumbleweed-oss-aarch64-Snapshot20240604
openSUSE-Tumbleweed-oss-armv7hl.license-Snapshot20240604
openSUSE-Tumbleweed-oss-armv7hl-Snapshot20240604
openSUSE-Tumbleweed-oss-aarch64-Snapshot20240604-debuginfo
openSUSE-Tumbleweed-oss-armv7hl-Snapshot20240604-debuginfo
openSUSE-Tumbleweed-oss-aarch64-Snapshot20240604-source
openSUSE-Tumbleweed-oss-armv7hl-Snapshot20240604-source}
P:obs/openSUSE:Factory:ARM:ToTest/jeos-aarch64/ test_before_after_diff.sh
```

**Comment by mloviska** [comment]
Can we move this PR forward, guys?

**Comment by ricardobranco777** [comment]
> Can we move this PR forward, guys?

I don't have merge rights.

**Comment by ggardet** [comment]
All LGTM.

**Comment by mloviska** [comment]
Sorry, I was missing all repos in `t/obs/openSUSE:Factory:ARM:ToTest/base/files_repo_openSUSE-ftp-ftp.lst` hence I had to split the base batch. If there is a better way, I am opened to suggestions. Thanks

**Review by grisu48 — APPROVED** [review]

**Comment by mloviska** [comment]
Can we merge this, please?

**Pull request merged**
